# ============================
# Configuracion Micro Servicio
# ============================
spring.application.name=OperacionInventario
server.port=8530


# ============================
# LOGS
# ============================
logging.level.root=INFO
logging.level.com.ope.inv=DEBUG


# ============================
# DATASOURCE
# ============================
spring.datasource.driver-class-name=org.firebirdsql.jdbc.FBDriver
spring.datasource.url=jdbc:firebird://localhost:3050/C:/Aplicativos/BDFirebird/OPERACIONGENERAL.FDB
spring.datasource.username=USROPE
spring.datasource.password=Ejecutor


# ============================
# HIKARI CONNECTION POOL
# ============================
spring.datasource.hikari.pool-name=HikariPool-OperacionInv
spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.minimum-idle=3
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=45000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.auto-commit=true


# ============================
# Configuacion de conexion
# ============================
spring.datasource.hikari.connection-test-query=SELECT 1 FROM RDB$DATABASE
spring.sql.init.mode=never